# Generated by Django 2.2.4 on 2019-08-31 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.CreateModel(
            name='TestExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_code', models.CharField(max_length=10, unique=True, verbose_name='Код ордена')),
            ],
            options={
                'verbose_name': 'Тестовое испытание',
                'verbose_name_plural': 'Тестовые испытания',
            },
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siths', to='sith.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Ситх',
                'verbose_name_plural': 'Ситхи',
            },
        ),
        migrations.CreateModel(
            name='Recruter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_shadow_hand', models.BooleanField(default=False, verbose_name='Рука тени')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruters', to='sith.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Рекрутер',
                'verbose_name_plural': 'Рекрутеры',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание вопроса')),
                ('test_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sith.TestExam', verbose_name='Тестовое испытание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='Да')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sith.Question', verbose_name='Вопрос')),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sith.Recruter', verbose_name='Рекрутер')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
