# Generated by Django 2.2.4 on 2019-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sith', '0004_auto_20191110_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='recruters_count',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Возраст'),
        ),
    ]
