# Generated by Django 2.2.4 on 2019-11-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sith', '0006_auto_20191110_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruter',
            name='is_shadow_hand',
        ),
        migrations.RemoveField(
            model_name='sith',
            name='recruters_count',
        ),
    ]
